version: '3'
services:
  my-app:
    image: openjdk:11-jre
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build/libs:/app/build/libs
    command: ["java", "-jar", "/app/build/libs/S3Upload_SNU-0.0.1-SNAPSHOT.jar"]
