cloud:
  aws:
    s3:
      bucket:
      - ${uploadBucket} upload-snu
      - ${downBucket} down-snu
    credentials:
      access-key: ${access}
      secret-key: ${secret}
    region:
      static: ${AWS_REGION}

    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
server:
  port: 8080