cloud:
  aws:
    s3:
      bucket:
      - 
      -
    credentials:
      access-key:
      secret-key: 
    region:
      static: 

    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

server:
  port: 8081
  address: 127.0.0.1
