cloud:
  aws:
    s3:
      bucket:
      - upload-snu
      - down-snu
    credentials:
      access-key: AKIAZ6RPDHXFNB6EKUMZ
      secret-key: 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
    region:
      static: ap-northeast-2

    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

server:
  port: 8081
  address: 127.0.0.1