spring:
  datasource:
    username: ${DBNAME}
    password: ${DBPassword}
    url: ${DBURL}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${redisHost}
      port: ${redisPort}
      password: ${redisPwd}

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    header: Authorization
    secret: ${jwt_secret}
    token-validity-in-seconds: 604800

cloud:
  aws:
    s3:
      bucket:
      - ${uploadBucket}
      - ${downBucket}
    credentials:
      access-key: ${access}
      secret-key: ${secret}
    region:
      static: ${region}

    stack:
      auto: false
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
server:
  port: 8080